export PATH="/usr/local/mysql/bin:$PATH"
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

alias ga='git add -A'
alias gc='git commit -a'
alias gcm='git commit -a -m'
alias gu='git pull'
alias gp='git push'
alias gcp='git cherry-pick'
alias gco='git checkout'
alias gb='git branch'
alias gss='git stash save'
alias gsa='git stash apply'
alias gsl='git stash lists'
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"  # This loads RVM into a shell session.

##
# Your previous /Users/isaac/.bash_profile file was backed up as /Users/isaac/.bash_profile.macports-saved_2011-07-22_at_14:48:35
# [[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"  # Load RVM into a shell session *as a function*
eval "$(rbenv init -)"
eval "$(rbenv init -)"
eval "$(rbenv init -)"
eval "$(rbenv init -)"
eval "$(rbenv init -)"
